### PR TITLE
ci(components): provide a standalone JS bundle

### LINKED ISSUE #399: Build standalone bundle
It would be great to have a standalone bundle that can be easily used without any other dependencies. It should be made available on NPM so that people can use it like this:

```html
<html>
  <head>
    <script type="module" src="https://unpkg.com/@genspectrum/dashboard-components@...."></script>
    <link rel="stylesheet" href="https://unpkg.com/@genspectrum/dashboard-components@...." />
  </head>
  <body>
    <gs-app...
  </body>
</html>
```

(unpkg.com automatically deploys everything that is on NPM. Our current dashboard-components.js is available at https://unpkg.com/@genspectrum/dashboard-components@0.6.8/dist/dashboard-components.js.)

### PR DESCRIPTION
**Pull request by chaoran-chen**
resolves #399

### Summary

This PR changes the vite release config to create a bundle that includes all dependencies.

@fengelniederhammer, @JonasKellerer, do you see some disadvantages of doing that?

### CODE REVIEW

**Comment by chaoran-chen** [comment]
I'll merge this without reviews as it is otherwise blocking me. Please share if you have concerns about this change!

**Comment by fengelniederhammer** [comment]
Did you check what the result of the built output is?

Does the bundled output contain all dependencies? Are some maybe still missing?

A potential disadvantage that I can think of is that the dependencies of this library are bundled into the output so that consuming code can't reuse them (if they use the same libraries).

**Comment by chaoran-chen** [comment]
It seems to contain everything, this codepen works: https://codepen.io/chaoran-chen/pen/KKjNdwj?editors=1000

**Comment by fengelniederhammer** [comment]
This increased the library size by a factor of 4:

Before:
```
[vite:dts] Start generate declaration files...
dist/style.css                106.30 kB │ gzip: 18.97 kB
dist/dashboard-components.js  325.63 kB │ gzip: 64.53 kB │ map: 536.13 kB
``` 

After:
```
[vite:dts] Start generate declaration files...
dist/style.css                  106.30 kB │ gzip:  18.97 kB
dist/dashboard-components.js  1,289.58 kB │ gzip: 274.41 kB │ map: 2,439.80 kB
```

**Comment by chaoran-chen** [comment]
We could, in the future, build two bundles, one with and one without external dependencies.

**Pull request merged**
