### PR TITLE
docs(components): mention how to install and use the components in the Storybook introduction

### PR DESCRIPTION
**Pull request by fengelniederhammer**
### Summary

I noticed that the introduction page of our Storybook docs is a bit sparse for someone who doesn't know the components.

### Screenshot

image

### PR Checklist

- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

### CODE REVIEW

**Comment by chaoran-chen** [comment]
I think that there is no link to the GitHub, right? Would make sense to add one, I think.

**Comment by fengelniederhammer** [comment]
I didn't really know where to put the link, so I put it in the top right corner. Suggestions are welcome :)

grafik

**Comment by JonasKellerer** [comment]
> I didn't really know where to put the link, so I put it in the top right corner. Suggestions are welcome :)
Seems good to me. If there are more links, we could add them next to this.

**Review by JonasKellerer — APPROVED** [review]
LGTM

**Pull request merged**
